In [1]:
import pandas as pd
%matplotlib inline

In [2]:
data = pd.read_csv('TAP-PD_Kinetics_Device_Testing.csv')
data

,PATNO,TESTDATE,TAPDAY,REVISION,DEVICESN,QMAT_OMS,QMAT_KEYDOWN,QMAT_KEYDOWN_RIGHT,QMAT_KEYDOWN_LEFT,QMAT_PEGCYCLE,QMAT_PEGCYCLE_RIGHT,QMAT_PEGCYCLE_LEFT,QMAT_KEYTRAN,QMAT_KEYTRAN_RIGHT,QMAT_KEYTRAN_LEFT,DOM_SIDE,AFF_SIDE,SEX,CONTROL,NOTES
0,3432,09/2011,0.0,R4,HVDG9341016,40.462,3.717,3.633,3.793,0.808,0.844,0.770,-0.980,-1.372,-0.699,NaN,NaN,Male,False,"Pegboard test, right hand--Some pegs were remo..."
1,3432,09/2011,7.0,R4,HVDG9341016,41.180,3.590,3.495,3.677,0.750,0.785,0.713,-0.981,-1.091,-0.883,NaN,NaN,Male,False,NaN
2,3432,09/2011,14.0,R4,HVDG9341016,41.975,3.506,3.356,3.636,0.704,0.715,0.694,-0.904,-1.017,-0.802,NaN,NaN,Male,False,"Pegboard test, right hand--Some pegs were remo..."
3,3435,10/2011,0.0,R4,HVDG9353016,46.176,3.765,3.438,4.012,1.002,1.072,0.927,-0.417,-0.144,-0.794,NaN,NaN,NaN,False,NaN
4,3218,10/2011,0.0,R4,HVDG9341013,39.231,4.139,4.464,3.655,0.941,0.809,1.057,-0.578,-0.697,-0.472,Right,Left,Male,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,3088,04/2014,375.0,R4,HVDG9341020,31.757,4.285,4.492,4.025,0.676,0.431,0.872,-0.766,-0.920,-0.633,NaN,NaN,Female,False,NaN
499,3089,04/2014,362.0,R4,HVDG9353019,32.667,3.908,4.109,3.654,0.755,0.699,0.809,-1.772,-1.782,-1.761,NaN,NaN,Female,False,NaN
500,3234,06/2014,458.0,R4,HVDG9353015,34.305,4.063,4.189,3.920,0.734,0.700,0.766,-1.025,-1.044,-1.006,Right,Left,Male,False,"Keyboard test, right hand--Times of key data a..."
501,3086,10/2014,NaN,R4,HVDG9343006,22.716,4.747,4.897,4.570,0.680,0.574,0.776,-1.296,-1.366,-1.230,Right,Left,Female,False,NaN
502,3086,03/2015,NaN,R4,HVDG9343006,25.106,4.772,4.897,4.630,0.826,0.823,0.828,-1.246,-1.313,-1.184,Right,Left,Female,False,NaN

In [3]:
data.columns
# Feature들 종류

Index(['PATNO', 'TESTDATE', 'TAPDAY', 'REVISION', 'DEVICESN', 'QMAT_OMS',
       'QMAT_KEYDOWN', 'QMAT_KEYDOWN_RIGHT', 'QMAT_KEYDOWN_LEFT',
       'QMAT_PEGCYCLE', 'QMAT_PEGCYCLE_RIGHT', 'QMAT_PEGCYCLE_LEFT',
       'QMAT_KEYTRAN', 'QMAT_KEYTRAN_RIGHT', 'QMAT_KEYTRAN_LEFT', 'DOM_SIDE',
       'AFF_SIDE', 'SEX', 'CONTROL', 'NOTES'],
      dtype='object')

In [4]:
del data['NOTES']
del data['TESTDATE']
del data['REVISION']
del data['DEVICESN']
data
#  쓸모없는 데이터 제거 (판단 근거는 나중에 알려줄게,,)
#  ''안에 들어간 feature는 useless feature로 판단

,PATNO,TAPDAY,QMAT_OMS,QMAT_KEYDOWN,QMAT_KEYDOWN_RIGHT,QMAT_KEYDOWN_LEFT,QMAT_PEGCYCLE,QMAT_PEGCYCLE_RIGHT,QMAT_PEGCYCLE_LEFT,QMAT_KEYTRAN,QMAT_KEYTRAN_RIGHT,QMAT_KEYTRAN_LEFT,DOM_SIDE,AFF_SIDE,SEX,CONTROL
0,3432,0.0,40.462,3.717,3.633,3.793,0.808,0.844,0.770,-0.980,-1.372,-0.699,NaN,NaN,Male,False
1,3432,7.0,41.180,3.590,3.495,3.677,0.750,0.785,0.713,-0.981,-1.091,-0.883,NaN,NaN,Male,False
2,3432,14.0,41.975,3.506,3.356,3.636,0.704,0.715,0.694,-0.904,-1.017,-0.802,NaN,NaN,Male,False
3,3435,0.0,46.176,3.765,3.438,4.012,1.002,1.072,0.927,-0.417,-0.144,-0.794,NaN,NaN,NaN,False
4,3218,0.0,39.231,4.139,4.464,3.655,0.941,0.809,1.057,-0.578,-0.697,-0.472,Right,Left,Male,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,3088,375.0,31.757,4.285,4.492,4.025,0.676,0.431,0.872,-0.766,-0.920,-0.633,NaN,NaN,Female,False
499,3089,362.0,32.667,3.908,4.109,3.654,0.755,0.699,0.809,-1.772,-1.782,-1.761,NaN,NaN,Female,False
500,3234,458.0,34.305,4.063,4.189,3.920,0.734,0.700,0.766,-1.025,-1.044,-1.006,Right,Left,Male,False
501,3086,NaN,22.716,4.747,4.897,4.570,0.680,0.574,0.776,-1.296,-1.366,-1.230,Right,Left,Female,False
502,3086,NaN,25.106,4.772,4.897,4.630,0.826,0.823,0.828,-1.246,-1.313,-1.184,Right,Left,Female,False

In [5]:
patno = data['PATNO']
patno
# patient number

0      3432
1      3432
2      3432
3      3435
4      3218
       ...
498    3088
499    3089
500    3234
501    3086
502    3086
Name: PATNO, Length: 503, dtype: int64

In [6]:
patno.value_counts()
# 같은사람이 여러번 한 것 같음

4102    75
3234    22
3076    21
3230    20
3220    20
3227    19
3218    18
3083    18
3433    17
3440    17
3223    17
3436    16
3078    16
3089    16
3228    16
4051    16
3435    15
3443    15
3439    14
3224    14
4059    14
3229    13
3077    13
4103    13
3233    12
3432     8
4096     7
3088     7
3448     5
3086     4
3225     3
3226     2
Name: PATNO, dtype: int64

In [7]:
df1 = data.loc[patno.isin(['3432'])]
df2 = df1.drop(['DOM_SIDE','AFF_SIDE'],axis=1)
df2
# 동일 환자 여러번 실험

,PATNO,TAPDAY,QMAT_OMS,QMAT_KEYDOWN,QMAT_KEYDOWN_RIGHT,QMAT_KEYDOWN_LEFT,QMAT_PEGCYCLE,QMAT_PEGCYCLE_RIGHT,QMAT_PEGCYCLE_LEFT,QMAT_KEYTRAN,QMAT_KEYTRAN_RIGHT,QMAT_KEYTRAN_LEFT,SEX,CONTROL
0,3432,0.0,40.462,3.717,3.633,3.793,0.808,0.844,0.770,-0.980,-1.372,-0.699,Male,False
1,3432,7.0,41.180,3.590,3.495,3.677,0.750,0.785,0.713,-0.981,-1.091,-0.883,Male,False
2,3432,14.0,41.975,3.506,3.356,3.636,0.704,0.715,0.694,-0.904,-1.017,-0.802,Male,False
5,3432,20.0,48.058,3.408,3.257,3.539,0.864,0.983,0.729,-0.526,-0.539,-0.513,Male,False
6,3432,38.0,43.499,3.640,3.586,3.690,0.821,0.837,0.804,-0.655,-0.671,-0.639,Male,False
7,3432,117.0,46.379,3.478,3.422,3.531,0.974,1.022,0.923,-0.998,-1.246,-0.799,Male,False
73,3432,193.0,45.592,3.590,3.390,3.756,0.961,1.052,0.862,-0.828,-0.813,-0.844,Male,False
220,3432,354.0,47.818,3.366,3.210,3.501,0.906,0.909,0.902,-0.799,-0.964,-0.657,Male,False

In [8]:
del data['DOM_SIDE']
del data['AFF_SIDE']
data
# 데이터 전처리 초안 틀

,PATNO,TAPDAY,QMAT_OMS,QMAT_KEYDOWN,QMAT_KEYDOWN_RIGHT,QMAT_KEYDOWN_LEFT,QMAT_PEGCYCLE,QMAT_PEGCYCLE_RIGHT,QMAT_PEGCYCLE_LEFT,QMAT_KEYTRAN,QMAT_KEYTRAN_RIGHT,QMAT_KEYTRAN_LEFT,SEX,CONTROL
0,3432,0.0,40.462,3.717,3.633,3.793,0.808,0.844,0.770,-0.980,-1.372,-0.699,Male,False
1,3432,7.0,41.180,3.590,3.495,3.677,0.750,0.785,0.713,-0.981,-1.091,-0.883,Male,False
2,3432,14.0,41.975,3.506,3.356,3.636,0.704,0.715,0.694,-0.904,-1.017,-0.802,Male,False
3,3435,0.0,46.176,3.765,3.438,4.012,1.002,1.072,0.927,-0.417,-0.144,-0.794,NaN,False
4,3218,0.0,39.231,4.139,4.464,3.655,0.941,0.809,1.057,-0.578,-0.697,-0.472,Male,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,3088,375.0,31.757,4.285,4.492,4.025,0.676,0.431,0.872,-0.766,-0.920,-0.633,Female,False
499,3089,362.0,32.667,3.908,4.109,3.654,0.755,0.699,0.809,-1.772,-1.782,-1.761,Female,False
500,3234,458.0,34.305,4.063,4.189,3.920,0.734,0.700,0.766,-1.025,-1.044,-1.006,Male,False
501,3086,NaN,22.716,4.747,4.897,4.570,0.680,0.574,0.776,-1.296,-1.366,-1.230,Female,False
502,3086,NaN,25.106,4.772,4.897,4.630,0.826,0.823,0.828,-1.246,-1.313,-1.184,Female,False

#### Label 값은 Derived_Variable_Definitions_and_Score_Calculations.csv에서 확인하기

#### CTRL + F 누르고 원하는 환자 클릭(ex. 3432)

#### Label 값이 들어가면 대충 틀은 잡힘. (전처리 더 해줘야되는데 일단 초안으로)